### ISSUE TITLE
Can u use flow messages?

### ISSUE THREAD

**Issue by Darker935** [kodepandai/whatsapp-api#4]
Are u using flow messages? like [**this messages**](https://developers.facebook.com/docs/whatsapp/flows/examples/templates)

**Comment by axmad386** [comment]
Hi, thanks for opening issue. Currently we don't implement flow messages. It's need verified business whatsapp account and we cannot do that atm. Actually this wrapper just for internal purpose, and we doesn't use it for now, bu there is possibility that we will add the flow messages in the future

**Comment by Darker935** [comment]
Ok, thx
